package com.company.payroll.controller;

import com.company.payroll.dto.EmployeeResponseDto;
import com.company.payroll.dto.OnboardingRequestDto;
import com.company.payroll.dto.OnboardingResponseDto;
import com.company.payroll.service.EmployeeService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/v1/employees")
@RequiredArgsConstructor
public class EmployeeController {

    private final EmployeeService employeeService;

    /**
     * Onboard a new employee into the payroll system.
     * This API creates a new employee record along with salary structure.
     * Employee code is auto-generated by the system.
     */
    @PostMapping
    public ResponseEntity<OnboardingResponseDto> onBoardNewEmployee(
            @RequestBody OnboardingRequestDto request) {

        return ResponseEntity
                .status(HttpStatus.CREATED)
                .body(employeeService.onBoardNewEmployee(request));
    }

    /**
     * Update an existing employee record.
     * Employee is identified using employee code.
     * Salary structure will be updated if provided.
     */
    @PutMapping("/{empCode}")
    public ResponseEntity<OnboardingResponseDto> updateEmployeeRecord(
            @PathVariable String empCode,
            @RequestBody OnboardingRequestDto request) {

        return ResponseEntity.ok(
                employeeService.updateEmployeeRecord(empCode, request)
        );
    }

    /**
     * Soft delete an employee.
     * Employee will be marked inactive instead of permanent deletion.
     * Payroll and audit history remains intact.
     */
    @DeleteMapping("/{empCode}")
    public ResponseEntity<Void> deleteEmployeeRecord(
            @PathVariable String empCode) {

        employeeService.deleteEmployeeRecord(empCode);
        return ResponseEntity.noContent().build();
    }

    /**
     * Fetch all active employees.
     * Returns only employees who are currently active in the system.
     */
    @GetMapping
    public ResponseEntity<List<EmployeeResponseDto>> getAllActiveEmployees() {

        return ResponseEntity.ok(
                employeeService.getAllActiveEmployees()
        );
    }

    /**
     * Fetch  active employees based on their emp code
     * Returns only employees who are currently active in the system.
     */
    @GetMapping("/{empCode}")
    public ResponseEntity<EmployeeResponseDto> getActiveEmployeeByEmpCode(@PathVariable String empCode) {
        return ResponseEntity.ok(
                employeeService.getActiveEmployeeByEmpCode(empCode));
    }
}
